### ISSUE TITLE
Design Rework

### ISSUE THREAD

**Issue by LuisMossburger** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-bib-buddy#100]
Rework the design of the whole app to better fit with our initial layout proposal #8 and look "finished".

**Comment by xSabrina** [comment]
Our **check-Buttons** on several app locations are **overlapped by the System Keyboard**, which is badly usable since you have to close the keyboard to use them. Maybe move it to the right upper corner just below the header?

**Comment by xSabrina** [comment]
Maybe change the string for searching books online from "Im Online-Katalog suchen" to "Online per ISBN suchen", because users might think they could search for a book in general (e.g. by title).

**Comment by LuisMossburger** [comment]
See #118 for an extensive list of all problems and the progress regarding this issue.

**Comment by claudia3** [comment]
Change the rename shelf Dialog to a separate Fragment to make the changing of data consistent.
