### ISSUE TITLE
UI rework ideas/suggestions

### ISSUE THREAD

**Issue by xSabrina** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-bib-buddy#118]
Here are some things that should be changed on our app UI (at least in my opinion):

1. The **addButton** (now red circle and black plus in it) should be **changed to our blue color and a white plus** in it.
2. **Toasts are semi transparent** and overlap our bottom-navigation which is causing bad readability - we should **increase the toast alpha**.
3. On **SearchFragment the Magnifier Icon** has a strange **background** (needs to be set to null).
4. **Title text on using the export button** without something to export should be changed from "Das Regal ist leer/keine Bücher im Regal") to only **"Das Regal ist leer"**.
5. **ExportButtons position** in the header needs to be fixed to align right (next to the optionsMenu-points).
6. **ExportButtons color** should be changed to black to be consistent in clickable buttons (matching the optionsMenu-points).
7. **Export-items in all optionMenus should be removed**, because there are separate exportButtons next to the optionMenu-points.
8. **Deleting/Sort-items** in optionMenus should **only be visible/available**, when they are usable - means: only when **any item is selected** (I remember that this is not the case in at least NotesFragment and BookNotesFragment).

**Comment by LuisMossburger** [comment]
Agree with all points, except the first - our primary color is the red, therefore our primary buttons should have the same color, don't you think?

Also:
* Integrated help texts should be way shorter
* I think buttons in the header should not be black but rather a mid grey, so they don't distract as much
* I'll try to adjust the sizing of individual items a bit. I have the feeling a slightly smaller header would look better for example

**Comment by SarahKurek** [comment]
Also the hard coded lengths and spacing in the xml should be changed, as these can cause problems with different display sizes/resolutions.

**Comment by LuisMossburger** [comment]
Team meeting: Buttons in Header, default invisible => also set invisible in "onPause" methods in fragments

**Comment by xSabrina** [comment]
> Agree with all points, except the first - our primary color is the red, therefore our primary buttons should have the same color, don't you think?

Our check-Button on creating shelfs is in our blue-ish design color as well - but indeed, this would work as well, but make the inner cross white then? It looks a bit strange with the black one.

>     * I think buttons in the header should not be black but rather a mid grey, so they don't distract as much

Buttons should never be gray - this is against conventions, users will expect it to be disabled. You can use any other color though - choose any of our design colors? Like the redish one we use in other contexts as button color already.

>     * I'll try to adjust the sizing of individual items a bit. I have the feeling a slightly smaller header would look better for example

Agreed.

**Comment by xSabrina** [comment]
>     8. **Deleting/Sort-items** in optionMenus should **only be visible/available**, when they are usable - means: only when **any item is selected** (I remember that this is not the case in at least NotesFragment and BookNotesFragment).

This is done with one of the last merges and the open PR #117.

**Comment by LuisMossburger** [comment]
ToDo for design rework:

- [ ] consistent layout for all form buttons
- [ ] consistent layout for header icons & menu
- [ ] rework help texts in fragments themselves
- [ ] rework help texts in help section
- [ ] rework size of bottom nav and header
- [ ] rework "app design" (meaning app icon, start up etc)
- [ ] rework the home fragment (maybe another PR needed for that)
- [ ] consistent, more subtle use of colors (pink overused at the moment)
- [ ] rework toasts (e.g. not transparent)
- [ ] consistent layout for search bars
- [ ] consistent formulations for everything in strings.xml

**Comment by xSabrina** [comment]
There is too much empty space between the header and the first note cardView in BookNotesView.

**Comment by xSabrina** [comment]
The NoteType icons in the note card views (microphone and document) are still black and white ones from a different set. I suggest to replace them by ones of the colored icon set that we use for our other card views to be consistent in our list item designs.

**Comment by LuisMossburger** [comment]
> 
> 
> The NoteType icons in the note card views (microphone and document) are still black and white ones. I suggest to replace them by ones of the colored icon set that we use for our other card views to be consistent in our list item designs.

The document should still have the colored icon in the current dev, the microphone was just replaced by me in my branch - will be in the next PR! :)

**Comment by LuisMossburger** [comment]
All aspects were adressed and merged in the last 6 design PRs. Can be closed now! :)
