### ISSUE TITLE
Searching by ISBN with empty spaces is causing the search to fail

### ISSUE THREAD

**Issue by xSabrina** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-bib-buddy#133]
Searching for a book by ISBN with empty spaces (e.g. when copying ISBNs containing white spaces) is causing the search to fail.
On performing the search empty spaces should be removed from the input automatically.

**Comment by LuisMossburger** [comment]
As far as I can tell, there are more problems here, e.g. if one enters an ISBN with "-". Proper validation of ISBNs is not given here - will make a new branch and correct that. Thanks!
