### ISSUE TITLE
Notes cannot be renamed

### ISSUE THREAD

**Issue by claudia3** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-bib-buddy#159]
When a note is created and afterwards the user has no possibility to change the name of the note.

**Comment by LuisMossburger** [comment]
Is this true @claudia3? The name of the note is the first line of the note - if I alter the first line of the note, the name in lists is correctly updated.

**Comment by LuisMossburger** [comment]
Discussed & tested in team meeting: This actually works, therefore closing this issue :)
