### ISSUE TITLE
Display of audio notes in search list

### ISSUE THREAD

**Issue by LuisMossburger** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-bib-buddy#161]
**Description**
When searching for audio notes, these are displayed with a heading like "Sprachnotiz vom dd.mm.yyyy hh:mm" and with the document icon. Upon clicking, the text editor opens. The question also is - how should audionotes be searchable? They do not have a title, so should they show up when searching for the data of their respective book?

**Expected behavior**
For audio notes, the list view item from other lists (like in book note fragment) should be used. The respective icon (R.drawable.audionote) should be used and the audionote should be playable in the search list.

**Reproduce**
Add a shelf, a book and an audio note. In the search fragment, search for "Sprach" - the note will now show up. With a click on it, the text editor opens.

**Comment by claudia3** [comment]
As discussed a user can't search for an audio note because the name at the beginning is always the same "Sprachnotiz vom [Datum]".

**Comment by LuisMossburger** [comment]
Yeah, closing this after we discussed that a _text_ search for an _audio_ note doesn't really make sense... We have decided to skip audio notes in the search alltogether.

**Comment by claudia3** [comment]
I still have to create a PR to only fetch text notes.
